/* automatically generated by rust-bindgen 0.60.1 */

extern "C" {
    #[doc = " The main entry, argc and argv will be passed to the wasm module."]
    pub fn wasm_main(
        buf: *mut ::std::os::raw::c_uchar,
        size: ::std::os::raw::c_uint,
        argc: ::std::os::raw::c_int,
        argv: *mut *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
