// Generated by ecc -
#ifndef __STRUCT_UNMARSHAL_EVENT_H__
#define __STRUCT_UNMARSHAL_EVENT_H__

#include <string.h>

static void unmarshal_event__from_binary(struct event *dst, const void *src) {
    if (!src || !dst)
        return;
    dst->pid = *(unsigned int*)(src + 0);
    dst->tpid = *(unsigned int*)(src + 4);
    dst->sig = *(int*)(src + 8);
    dst->ret = *(int*)(src + 12);
    memcpy(dst->comm, src + 16, 16);
}

static void marshal_event__to_binary(void *dst, const struct event *src) {
    if (!src || !dst)
        return;
    *(unsigned int*)(dst + 0) = src->pid;
    *(unsigned int*)(dst + 4) = src->tpid;
    *(int*)(dst + 8) = src->sig;
    *(int*)(dst + 12) = src->ret;
    memcpy(dst + 16, src->comm, 16);
}

#endif /* __STRUCT_UNMARSHAL_EVENT_H__ */
