FROM ubuntu:22.04

WORKDIR /root/eunomia-bpf

RUN apt-get update && \
	apt-get install -y --no-install-recommends libelf1 libelf-dev \
		zlib1g-dev clang llvm libclang-13-dev make cmake git  wget tar && \
	apt-get install -y --no-install-recommends ca-certificates	&& \
	update-ca-certificates	&& \
	apt-get clean && \
	curl https://sh.rustup.rs -sSf | sh -s	&& \
	rm -rf /var/lib/apt/lists/*

COPY . /root/eunomia-bpf
RUN	make bpf-loader && make ecli

RUN	cp /root/eunomia-bpf/ecli/minimal/build/bin/Release/ecli /usr/bin/	&& \
	chmod +x /usr/bin/ecli

CMD ["/bin/bash"]