FROM ubuntu:22.04

ENV UBUNTU_SOURCE /etc/apt

WORKDIR /root

RUN apt-get update -y && \
	apt-get install -y --no-install-recommends libelf1 libelf-dev \
		zlib1g-dev clang llvm libclang-13-dev make cmake git  wget tar && \
	apt-get clean && \
	curl https://sh.rustup.rs -sSf | sh -s	&& \
	rm -rf /var/lib/apt/lists/*	&& \
	apt-get update	&& \
	apt-get install -y ca-certificates	&& \
	update-ca-certificates

RUN git clone --recurse-submodules https://github.com/eunomia-bpf/eunomia-bpf.git	&& \
	cd eunomia-bpf	&& \
	make bpf-loader	&& \
	make ecli

RUN	cp /root/eunomia-bpf/ecli/build/bin/Release/ecli /usr/bin/	&& \
	chmod +x /usr/bin/ecli

#CMD ecli run /root/my/package.json
CMD ["/bin/bash"]