[package]
name = "eunomia-rs"
version = "0.1.0"
edition = "2021"
description = "A rust binding for eunomia-bpf."
license = "MIT"

[dependencies]
anyhow = "1.0"
home = "0.5.4"

[lib]
crate-type = ["lib", "staticlib"]
