# SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
# Copyright (c) 2022, 郑昱笙，濮雯旭，张典典（牛校牛子队）

.PHONY:all
all: eunomia-bpf-runner

eunomia-bpf-runner:
	cd simple-runner && mkdir build && cd build && cmake .. && make
