FROM ubuntu:22.04

WORKDIR /usr/local/src
COPY . /usr/local/src

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        libelf1 libelf-dev zlib1g-dev libclang-13-dev \
        make wget curl python2 clang llvm pkg-config build-essential git && \
    apt-get install -y --no-install-recommends ca-certificates	&& \
	update-ca-certificates	&& \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget --progress=dot:giga --no-check-certificate \
        https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-17/wasi-sdk-17.0-linux.tar.gz && \
	tar -zxf wasi-sdk-17.0-linux.tar.gz && \
    rm wasi-sdk-17.0-linux.tar.gz   && \
	mkdir -p /opt/wasi-sdk/ && \
    mv wasi-sdk-17.0/* /opt/wasi-sdk/

RUN cp /usr/bin/python2 /usr/bin/python

RUN wget -nv -O - https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"
ARG CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

RUN make ecc    && \
    make -C compiler install    && \
    cd compiler/cmd && cargo clean

WORKDIR /usr/local/src/compiler

ENTRYPOINT ["make"]
CMD ["build"]
