[workspace]
resolver = "2"
members = [
    "bpf-loader-cli",
    "bpf-loader-lib",
    "bpf-loader-c-wrapper"
]

[profile.release]
opt-level = 3
# Turning lto to false allows `bpf-loader-c-wrapper` being linked into another rust program
# lto = true
debug = 0
overflow-checks = false
