
// Code generated by c-struct-bindgen and ecc - DO NOT EDIT
// See https://github.com/eunomia-bpf/c-struct-bindgen for details.
// struct-bindgen versions: 0.1.0
// source file path: bootstrap.bpf.o
#ifndef __STRUCT_MARSHAL_BOOTSTRAP_BPF_O_H__
#define __STRUCT_MARSHAL_BOOTSTRAP_BPF_O_H__
    
#include <assert.h>
#include <string.h>
#include <stdint.h>

struct event {
    int pid;
    int ppid;
    unsigned int exit_code;
    char __pad0[4];
    unsigned long long duration_ns;
    char comm[16];
    char filename[127];
    char __pad1[1];
    int exit_event;
    char __pad2[4];
} __attribute__((packed));

static_assert(sizeof(struct event) == 176, "Size of event2 is not 176");

#endif

