name: Build and test ewasm on Ubuntu

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2

    - name: get submodule
      run:  git submodule update --init --recursive

    - name: install deps
      run: |
          sudo make -C ecli install-deps

    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
        key: ${{ runner.os }}-dependencies

    - name: make ewasm
      run:  make ewasm

    - name: run unit tests
      run: |
        cd ewasm/
        sudo make test

    - name: run wasm generate tests
      run: |
        cd ewasm/
        sudo make test-wasm

    - name: Code coverage using Codecov
      run: bash <(curl -s https://codecov.io/bash)

