name: "Nix build check"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
      if: github.event_name != 'pull_request'

    - name: Nix Flake Show
      run: nix flake show --all-systems

    - name: Build ecc
      run: nix build .#ecc

    - name: Build ecli-rs
      run: nix build .#ecli-rs

    - name: Build bpftool
      run: nix build .#bpftool
